<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/build/css/style.css">
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">

            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#app-navbar-collapse">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="#">
                Meu Site com Silex
            </a>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">
            <ul class="nav navbar-nav">
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="/home">Home</a></li>
                <li><a href="/fale-conosco">Fale conosco</a></li>
                <li><a href="/admin/posts">Post</a></li>
            </ul>
        </div>
    </div>
</nav>
<?php echo $content; ?>
<script type="text/javascript" src="/build/js/jquery.min.js"></script>
<script type="text/javascript" src="/build/js/bootstrap.min.js"></script>
</body>
</html>